### ISSUE TITLE
How do I resolve this?

### ISSUE THREAD

**Issue by operationairstrike** [aorumbayev/autogpt4all#11]
![Screenshot_2023-06-14-15-29-02-162_com.termux-edit.jpg](https://github.com/aorumbayev/autogpt4all/assets/127621147/571b29e0-8fec-4551-92bf-9f97d6b633ee)

**Comment by aorumbayev** [comment]
@operationairstrike try:
```
cd LocalAI
make build
```

**Comment by operationairstrike** [comment]
Tysm
