### ISSUE TITLE
Error with docker and make when building localai

### ISSUE THREAD

**Issue by pehaem** [aorumbayev/autogpt4all#14]
getting this error with docker when building localai:

docker
ERROR: failed to solve: Unavailable: error reading from server: EOF

Make:
make[1]: *** [libgobert.a] Error 1
make: *** [go-bert/libgobert.a] Error 2

**Comment by aorumbayev** [comment]
@pehaem please refer to their repo for https://github.com/go-skynet/LocalAI/issues specific issues on localai

**Comment by pehaem** [comment]
sure
