### ISSUE TITLE
LocalAI doesnt have ./local-ai

### ISSUE THREAD

**Issue by apoordev** [aorumbayev/autogpt4all#2]
It looks like the LocalAI repo has removed the ./local-ai file and seems to have replaced it with just building the repo in docker. I got the script working after just manually building the LocalAI docker container.

Love the script btw!

**Comment by aorumbayev** [comment]
> It looks like the LocalAI repo has removed the ./local-ai file and seems to have replaced it with just building the repo in docker. I got the script working after just manually building the LocalAI docker container.
> 
> Love the script btw!

I believe the local-ai is not directory but an executable that is build after `make build` is executed in localai folder. Just retested with latest on main branch on localai and still works. Could be os specific as well, still works on linux and mac os. Closing issue for now as im unable to replicate the issue.

**Comment by apoordev** [comment]
Ooops yup out are correct, I'm on Linux and I didn't build the LocalAI repo so that explains not having the file.

Thanks!

**Comment by waplay** [comment]
I have the same problem on Linux (Ubuntu): after executing the script, ./local-ai is missing in the LocalAI folder. What should I do to fix this?

**Comment by apoordev** [comment]
Build the LocalAI repo locally using 'make build' or build the docker container with the instructions in the LocalAI readme. I didn't have luck using make build on fedora but I also didn't try very hard and preferred docker anyway.

**Comment by waplay** [comment]
> Build the LocalAI repo locally using 'make build' or build the docker container with the instructions in the LocalAI readme. I didn't have luck using make build on fedora but I also didn't try very hard and preferred docker anyway.

Ok, thank you!
