### ISSUE TITLE
Error while loading model

### ISSUE THREAD

**Issue by waplay** [aorumbayev/autogpt4all#3]
Error while loading model

After starting the server and AutoGPT, an error occurs:

`[127.0.0.1]:42798  404  -  GET      /
9:18PM DBG Request received: {"model":"gpt-3.5-turbo","file":"","language":"","response_format":"","size":"","prompt":null,"instruction":"","input":null,"stop":null,"messages":[{"role":"system","content":"\nYour task is to devise up to 5 highly effective goals and an appropriate role-based name (_GPT) for an autonomous agent, ensuring that the goals are optimally aligned with the successful completion of its assigned task.\n\nThe user will provide the task, you will provide only the output in the exact format specified below with no explanation or conversation.\n\nExample input:\nHelp me with marketing my business\n\nExample output:\nName: CMOGPT\nDescription: a professional digital marketer AI that assists Solopreneurs in growing their businesses by providing world-class expertise in solving marketing problems for SaaS, content products, agencies, and more.\nGoals:\n- Engage in effective problem-solving, prioritization, planning, and supporting execution to address your marketing needs as your virtual Chief Marketing Officer.\n\n- Provide specific, actionable, and concise advice to help you make informed decisions without the use of platitudes or overly wordy explanations.\n\n- Identify and prioritize quick wins and cost-effective campaigns that maximize results with minimal time and budget investment.\n\n- Proactively take the lead in guiding you and offering suggestions when faced with unclear information or uncertainty to ensure your marketing strategy remains on track.\n"},{"role":"user","content":"Task: 'create an advertising slogan for a drinking water company \"Darida\"'\nRespond only with the output in the exact format specified in the system prompt, with no explanation or conversation."}],"stream":false,"echo":false,"top_p":0,"top_k":0,"temperature":0,"max_tokens":0,"n":0,"batch":0,"f16":false,"ignore_eos":false,"repeat_penalty":0,"n_keep":0,"mirostat_eta":0,"mirostat_tau":0,"mirostat":0,"seed":0,"mode":0,"step":0}
9:18PM DBG Parameter Config: &{OpenAIRequest:{Model:gpt-3.5-turbo File: Language: ResponseFormat: Size: Prompt:<nil> Instruction: Input:<nil> Stop:<nil> Messages:[] Stream:false Echo:false TopP:0.7 TopK:80 Temperature:0.9 Maxtokens:512 N:0 Batch:0 F16:false IgnoreEOS:false RepeatPenalty:0 Keep:0 MirostatETA:0 MirostatTAU:0 Mirostat:0 Seed:0 Mode:0 Step:0} Name: StopWords:[] Cutstrings:[] TrimSpace:[] ContextSize:512 F16:false Threads:4 Debug:true Roles:map[] Embeddings:false Backend: TemplateConfig:{Completion: Chat: Edit:} MirostatETA:0 MirostatTAU:0 Mirostat:0 NGPULayers:0 ImageGenerationAssets: PromptStrings:[] InputStrings:[] InputToken:[]}
9:18PM DBG Loading model 'gpt-3.5-turbo' greedly
9:18PM DBG [llama] Attempting to load
9:18PM DBG Loading model llama from gpt-3.5-turbo
9:18PM DBG Loading model in memory from file: models/gpt-3.5-turbo
llama.cpp: loading model from models/gpt-3.5-turbo
error loading model: unrecognized tensor type 4

llama_init_from_file: failed to load model
9:18PM DBG [llama] Fails: failed loading model
9:18PM DBG [gpt4all-llama] Attempting to load
9:18PM DBG Loading model gpt4all-llama from gpt-3.5-turbo
9:18PM DBG Loading model in memory from file: models/gpt-3.5-turbo
SIGILL: illegal instruction
PC=0xb01f95 m=0 sigcode=2
signal arrived during cgo execution
instruction bytes: 0xc5 0xfd 0x6f 0x5 0xe3 0x97 0x24 0x0 0x49 0x8d 0x84 0x24 0xe8 0x14 0x0 0x0

goroutine 9 [syscall]:
runtime.cgocall(0x9e8710, 0xc0001ba268)
	/snap/go/current/src/runtime/cgocall.go:157 +0x5c fp=0xc0001ba240 sp=0xc0001ba208 pc=0x44a4fc
github.com/nomic-ai/gpt4all/gpt4all-bindings/golang._Cfunc_load_gptjllama_model(0x2dac800, 0x4)
	_cgo_gotypes.go:137 +0x4d fp=0xc0001ba268 sp=0xc0001ba240 pc=0x58892d
github.com/nomic-ai/gpt4all/gpt4all-bindings/golang.New({0xc00029c090, 0x14}, {0xc0002ac3e0, 0x2, 0x1?})
	/home/waplay/GitClone/autogpt4all/LocalAI/gpt4all/gpt4all-bindings/golang/gpt4all.go:35 +0x145 fp=0xc0001ba2c0 sp=0xc0001ba268 pc=0x588c45
github.com/go-skynet/LocalAI/pkg/model.gpt4allLM.func1({0xc00029c090?, 0xc58d80?})
	/home/waplay/GitClone/autogpt4all/LocalAI/pkg/model/initializers.go:110 +0x2a fp=0xc0001ba2f8 sp=0xc0001ba2c0 pc=0x608a0a
github.com/go-skynet/LocalAI/pkg/model.(*ModelLoader).LoadModel(0xc0001b2a50, {0xc000217960, 0xd}, 0xc0002c00e0)
	/home/waplay/GitClone/autogpt4all/LocalAI/pkg/model/loader.go:127 +0x1fe fp=0xc0001ba3f0 sp=0xc0001ba2f8 pc=0x60aa1e
github.com/go-skynet/LocalAI/pkg/model.(*ModelLoader).BackendLoader(0xc0001b2a50, {0xc4809d, 0xd}, {0xc000217960, 0xd}, {0xc0000145d8, 0x1, 0x1}, 0x4)
	/home/waplay/GitClone/autogpt4all/LocalAI/pkg/model/initializers.go:150 +0x7d2 fp=0xc0001ba4b8 sp=0xc0001ba3f0 pc=0x609412
github.com/go-skynet/LocalAI/pkg/model.(*ModelLoader).GreedyLoader(0xc0001b2a50, {0xc000217960, 0xd}, {0xc0000145d8, 0x1, 0x1}, 0x0?)
	/home/waplay/GitClone/autogpt4all/LocalAI/pkg/model/initializers.go:184 +0x3a5 fp=0xc0001ba600 sp=0xc0001ba4b8 pc=0x609a25
github.com/go-skynet/LocalAI/api.ModelInference({_, _}, _, {{{0xc000217960, 0xd}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...}, ...)
	/home/waplay/GitClone/autogpt4all/LocalAI/api/prediction.go:218 +0x145 fp=0xc0001ba8b0 sp=0xc0001ba600 pc=0x944545
github.com/go-skynet/LocalAI/api.ComputeChoices({0xc000035200, 0x5bd}, 0xc000150dc0, 0xc00025a280, 0xc0002092c0?, 0xc84278, 0x4?)
	/home/waplay/GitClone/autogpt4all/LocalAI/api/prediction.go:517 +0x138 fp=0xc0001bb060 sp=0xc0001ba8b0 pc=0x947c18
github.com/go-skynet/LocalAI/api.chatEndpoint.func2(0xc000134b00)
	/home/waplay/GitClone/autogpt4all/LocalAI/api/openai.go:361 +0x8ec fp=0xc0001bb220 sp=0xc0001bb060 pc=0x93f80c
github.com/gofiber/fiber/v2.(*App).next(0xc00013f200, 0xc000134b00)
	/home/waplay/go/pkg/mod/github.com/gofiber/fiber/v2@v2.45.0/router.go:144 +0x1bf fp=0xc0001bb2c8 sp=0xc0001bb220 pc=0x8c4dbf
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc000238330?)
	/home/waplay/go/pkg/mod/github.com/gofiber/fiber/v2@v2.45.0/ctx.go:913 +0x53 fp=0xc0001bb2e8 sp=0xc0001bb2c8 pc=0x8b0393
github.com/gofiber/fiber/v2/middleware/cors.New.func1(0xc000134b00)
	/home/waplay/go/pkg/mod/github.com/gofiber/fiber/v2@v2.45.0/middleware/cors/cors.go:162 +0x3da fp=0xc0001bb3f0 sp=0xc0001bb2e8 pc=0x8cabda
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc000061448?)
	/home/waplay/go/pkg/mod/github.com/gofiber/fiber/v2@v2.45.0/ctx.go:910 +0x43 fp=0xc0001bb410 sp=0xc0001bb3f0 pc=0x8b0383
github.com/gofiber/fiber/v2/middleware/recover.New.func1(0xc0000614e8?)
	/home/waplay/go/pkg/mod/github.com/gofiber/fiber/v2@v2.45.0/middleware/recover/recover.go:43 +0xcb fp=0xc0001bb488 sp=0xc0001bb410 pc=0x8d180b
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc0001b2ae0?)
	/home/waplay/go/pkg/mod/github.com/gofiber/fiber/v2@v2.45.0/ctx.go:910 +0x43 fp=0xc0001bb4a8 sp=0xc0001bb488 pc=0x8b0383
github.com/gofiber/fiber/v2/middleware/logger.New.func3(0xc000134b00)
	/home/waplay/go/pkg/mod/github.com/gofiber/fiber/v2@v2.45.0/middleware/logger/logger.go:121 +0x395 fp=0xc0001bbb30 sp=0xc0001bb4a8 pc=0x8cc455
github.com/gofiber/fiber/v2.(*App).next(0xc00013f200, 0xc000134b00)
	/home/waplay/go/pkg/mod/github.com/gofiber/fiber/v2@v2.45.0/router.go:144 +0x1bf fp=0xc0001bbbd8 sp=0xc0001bbb30 pc=0x8c4dbf
github.com/gofiber/fiber/v2.(*App).handler(0xc00013f200, 0x4cf317?)
	/home/waplay/go/pkg/mod/github.com/gofiber/fiber/v2@v2.45.0/router.go:171 +0x87 fp=0xc0001bbc38 sp=0xc0001bbbd8 pc=0x8c5007
github.com/gofiber/fiber/v2.(*App).handler-fm(0xc000238000?)
	<autogenerated>:1 +0x2c fp=0xc0001bbc58 sp=0xc0001bbc38 pc=0x8ca22c
github.com/valyala/fasthttp.(*Server).serveConn(0xc0001a4400, {0xd151a0?, 0xc000014540})
	/home/waplay/go/pkg/mod/github.com/valyala/fasthttp@v1.47.0/server.go:2365 +0x11d3 fp=0xc0001bbec8 sp=0xc0001bbc58 pc=0x84afb3
github.com/valyala/fasthttp.(*Server).serveConn-fm({0xd151a0?, 0xc000014540?})
	<autogenerated>:1 +0x39 fp=0xc0001bbef0 sp=0xc0001bbec8 pc=0x85a879
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc00011ba40, 0xc00003cf60)
	/home/waplay/go/pkg/mod/github.com/valyala/fasthttp@v1.47.0/workerpool.go:224 +0xa9 fp=0xc0001bbfa0 sp=0xc0001bbef0 pc=0x856aa9
github.com/valyala/fasthttp.(*workerPool).getCh.func1()
	/home/waplay/go/pkg/mod/github.com/valyala/fasthttp@v1.47.0/workerpool.go:196 +0x38 fp=0xc0001bbfe0 sp=0xc0001bbfa0 pc=0x856818
runtime.goexit()
	/snap/go/current/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001bbfe8 sp=0xc0001bbfe0 pc=0x4ad101
created by github.com/valyala/fasthttp.(*workerPool).getCh
	/home/waplay/go/pkg/mod/github.com/valyala/fasthttp@v1.47.0/workerpool.go:195 +0x1b0

goroutine 1 [IO wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/snap/go/current/src/runtime/proc.go:381 +0xd6 fp=0xc0001dd3f8 sp=0xc0001dd3d8 pc=0x47e2f6
runtime.netpollblock(0x7f654ef7c968?, 0x449b8f?, 0x0?)
	/snap/go/current/src/runtime/netpoll.go:527 +0xf7 fp=0xc0001dd430 sp=0xc0001dd3f8 pc=0x476c57
internal/poll.runtime_pollWait(0x7f65253bd498, 0x72)
	/snap/go/current/src/runtime/netpoll.go:306 +0x89 fp=0xc0001dd450 sp=0xc0001dd430 pc=0x4a79a9
internal/poll.(*pollDesc).wait(0xc00016cd00?, 0x4?, 0x0)
	/snap/go/current/src/internal/poll/fd_poll_runtime.go:84 +0x32 fp=0xc0001dd478 sp=0xc0001dd450 pc=0x51e712
internal/poll.(*pollDesc).waitRead(...)
	/snap/go/current/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc00016cd00)
	/snap/go/current/src/internal/poll/fd_unix.go:614 +0x2bd fp=0xc0001dd520 sp=0xc0001dd478 pc=0x52401d
net.(*netFD).accept(0xc00016cd00)
	/snap/go/current/src/net/fd_unix.go:172 +0x35 fp=0xc0001dd5d8 sp=0xc0001dd520 pc=0x5a97b5
net.(*TCPListener).accept(0xc000012810)
	/snap/go/current/src/net/tcpsock_posix.go:148 +0x25 fp=0xc0001dd600 sp=0xc0001dd5d8 pc=0x5bfb65
net.(*TCPListener).Accept(0xc000012810)
	/snap/go/current/src/net/tcpsock.go:297 +0x3d fp=0xc0001dd630 sp=0xc0001dd600 pc=0x5bec5d
github.com/valyala/fasthttp.acceptConn(0xc0001a4400, {0xd127c0, 0xc000012810}, 0xc0001dd828)
	/home/waplay/go/pkg/mod/github.com/valyala/fasthttp@v1.47.0/server.go:1930 +0x62 fp=0xc0001dd710 sp=0xc0001dd630 pc=0x849482
github.com/valyala/fasthttp.(*Server).Serve(0xc0001a4400, {0xd127c0?, 0xc000012810})
	/home/waplay/go/pkg/mod/github.com/valyala/fasthttp@v1.47.0/server.go:1823 +0x4f4 fp=0xc0001dd858 sp=0xc0001dd710 pc=0x848a94
github.com/gofiber/fiber/v2.(*App).Listen(0xc00013f200, {0xc3e8d4?, 0x7?})
	/home/waplay/go/pkg/mod/github.com/gofiber/fiber/v2@v2.45.0/listen.go:82 +0x110 fp=0xc0001dd8b8 sp=0xc0001dd858 pc=0x8bbeb0
main.main.func1(0xc000206160?)
	/home/waplay/GitClone/autogpt4all/LocalAI/main.go:97 +0x345 fp=0xc0001dd9b8 sp=0xc0001dd8b8 pc=0x975e25
github.com/urfave/cli/v2.(*Command).Run(0xc000206160, 0xc0000249c0, {0xc000024080, 0x4, 0x4})
	/home/waplay/go/pkg/mod/github.com/urfave/cli/v2@v2.25.3/command.go:274 +0x9eb fp=0xc0001ddc58 sp=0xc0001dd9b8 pc=0x963d2b
github.com/urfave/cli/v2.(*App).RunContext(0xc000202000, {0xd12b28?, 0xc0000280c8}, {0xc000024080, 0x4, 0x4})
	/home/waplay/go/pkg/mod/github.com/urfave/cli/v2@v2.25.3/app.go:332 +0x616 fp=0xc0001ddcc8 sp=0xc0001ddc58 pc=0x960b36
github.com/urfave/cli/v2.(*App).Run(...)
	/home/waplay/go/pkg/mod/github.com/urfave/cli/v2@v2.25.3/app.go:309
main.main()
	/home/waplay/GitClone/autogpt4all/LocalAI/main.go:101 +0xbae fp=0xc0001ddf80 sp=0xc0001ddcc8 pc=0x975a0e
runtime.main()
	/snap/go/current/src/runtime/proc.go:250 +0x207 fp=0xc0001ddfe0 sp=0xc0001ddf80 pc=0x47dec7
runtime.goexit()
	/snap/go/current/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001ddfe8 sp=0xc0001ddfe0 pc=0x4ad101

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/snap/go/current/src/runtime/proc.go:381 +0xd6 fp=0xc000050fb0 sp=0xc000050f90 pc=0x47e2f6
runtime.goparkunlock(...)
	/snap/go/current/src/runtime/proc.go:387
runtime.forcegchelper()
	/snap/go/current/src/runtime/proc.go:305 +0xb0 fp=0xc000050fe0 sp=0xc000050fb0 pc=0x47e130
runtime.goexit()
	/snap/go/current/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000050fe8 sp=0xc000050fe0 pc=0x4ad101
created by runtime.init.6
	/snap/go/current/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/snap/go/current/src/runtime/proc.go:381 +0xd6 fp=0xc000051780 sp=0xc000051760 pc=0x47e2f6
runtime.goparkunlock(...)
	/snap/go/current/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
	/snap/go/current/src/runtime/mgcsweep.go:278 +0x8e fp=0xc0000517c8 sp=0xc000051780 pc=0x46a50e
runtime.gcenable.func1()
	/snap/go/current/src/runtime/mgc.go:178 +0x26 fp=0xc0000517e0 sp=0xc0000517c8 pc=0x45f7c6
runtime.goexit()
	/snap/go/current/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000517e8 sp=0xc0000517e0 pc=0x4ad101
created by runtime.gcenable
	/snap/go/current/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000076000?, 0xd0add8?, 0x1?, 0x0?, 0x0?)
	/snap/go/current/src/runtime/proc.go:381 +0xd6 fp=0xc000051f70 sp=0xc000051f50 pc=0x47e2f6
runtime.goparkunlock(...)
	/snap/go/current/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x1136ce0)
	/snap/go/current/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000051fa0 sp=0xc000051f70 pc=0x468433
runtime.bgscavenge(0x0?)
	/snap/go/current/src/runtime/mgcscavenge.go:628 +0x45 fp=0xc000051fc8 sp=0xc000051fa0 pc=0x468a05
runtime.gcenable.func2()
	/snap/go/current/src/runtime/mgc.go:179 +0x26 fp=0xc000051fe0 sp=0xc000051fc8 pc=0x45f766
runtime.goexit()
	/snap/go/current/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000051fe8 sp=0xc000051fe0 pc=0x4ad101
created by runtime.gcenable
	/snap/go/current/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x1a0?, 0x11379c0?, 0x60?, 0x78?, 0xc000050770?)
	/snap/go/current/src/runtime/proc.go:381 +0xd6 fp=0xc000050628 sp=0xc000050608 pc=0x47e2f6
runtime.runfinq()
	/snap/go/current/src/runtime/mfinal.go:193 +0x107 fp=0xc0000507e0 sp=0xc000050628 pc=0x45e807
runtime.goexit()
	/snap/go/current/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000507e8 sp=0xc0000507e0 pc=0x4ad101
created by runtime.createfing
	/snap/go/current/src/runtime/mfinal.go:163 +0x45

goroutine 6 [select]:
runtime.gopark(0xc000052750?, 0x2?, 0x0?, 0x0?, 0xc0000526cc?)
	/snap/go/current/src/runtime/proc.go:381 +0xd6 fp=0xc00005cd20 sp=0xc00005cd00 pc=0x47e2f6
runtime.selectgo(0xc00005cf50, 0xc0000526c8, 0x0?, 0x0, 0x0?, 0x1)
	/snap/go/current/src/runtime/select.go:327 +0x7be fp=0xc00005ce60 sp=0xc00005cd20 pc=0x48dade
github.com/go-skynet/LocalAI/api.(*galleryApplier).start.func1()
	/home/waplay/GitClone/autogpt4all/LocalAI/api/gallery.go:57 +0xe5 fp=0xc00005cfe0 sp=0xc00005ce60 pc=0x93d305
runtime.goexit()
	/snap/go/current/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00005cfe8 sp=0xc00005cfe0 pc=0x4ad101
created by github.com/go-skynet/LocalAI/api.(*galleryApplier).start
	/home/waplay/GitClone/autogpt4all/LocalAI/api/gallery.go:55 +0xaa

goroutine 7 [sleep]:
runtime.gopark(0x144a367dc3a8?, 0xc000052f88?, 0x5?, 0xd8?, 0xc00011ba70?)
	/snap/go/current/src/runtime/proc.go:381 +0xd6 fp=0xc000052f58 sp=0xc000052f38 pc=0x47e2f6
time.Sleep(0x2540be400)
	/snap/go/current/src/runtime/time.go:195 +0x135 fp=0xc000052f98 sp=0xc000052f58 pc=0x4a9f75
github.com/valyala/fasthttp.(*workerPool).Start.func2()
	/home/waplay/go/pkg/mod/github.com/valyala/fasthttp@v1.47.0/workerpool.go:67 +0x56 fp=0xc000052fe0 sp=0xc000052f98 pc=0x855f76
runtime.goexit()
	/snap/go/current/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000052fe8 sp=0xc000052fe0 pc=0x4ad101
created by github.com/valyala/fasthttp.(*workerPool).Start
	/home/waplay/go/pkg/mod/github.com/valyala/fasthttp@v1.47.0/workerpool.go:59 +0xdd

goroutine 18 [IO wait]:
runtime.gopark(0x0?, 0xb?, 0x0?, 0x0?, 0x7?)
	/snap/go/current/src/runtime/proc.go:381 +0xd6 fp=0xc0001b7a28 sp=0xc0001b7a08 pc=0x47e2f6
runtime.netpollblock(0x4c0b65?, 0x449b8f?, 0x0?)
	/snap/go/current/src/runtime/netpoll.go:527 +0xf7 fp=0xc0001b7a60 sp=0xc0001b7a28 pc=0x476c57
internal/poll.runtime_pollWait(0x7f65253bd3a8, 0x72)
	/snap/go/current/src/runtime/netpoll.go:306 +0x89 fp=0xc0001b7a80 sp=0xc0001b7a60 pc=0x4a79a9
internal/poll.(*pollDesc).wait(0xc00009e000?, 0xc00028c000?, 0x0)
	/snap/go/current/src/internal/poll/fd_poll_runtime.go:84 +0x32 fp=0xc0001b7aa8 sp=0xc0001b7a80 pc=0x51e712
internal/poll.(*pollDesc).waitRead(...)
	/snap/go/current/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00009e000, {0xc00028c000, 0x1000, 0x1000})
	/snap/go/current/src/internal/poll/fd_unix.go:167 +0x299 fp=0xc0001b7b40 sp=0xc0001b7aa8 pc=0x51faf9
net.(*netFD).Read(0xc00009e000, {0xc00028c000?, 0xc0000a2088?, 0xc0000a2000?})
	/snap/go/current/src/net/fd_posix.go:55 +0x29 fp=0xc0001b7b88 sp=0xc0001b7b40 pc=0x5a7629
net.(*conn).Read(0xc00009a008, {0xc00028c000?, 0xc00009a008?, 0xc00028d000?})
	/snap/go/current/src/net/net.go:183 +0x45 fp=0xc0001b7bd0 sp=0xc0001b7b88 pc=0x5b6b25
net.(*TCPConn).Read(0xc0001a45e0?, {0xc00028c000?, 0x83a32f?, 0x83d485?})
	<autogenerated>:1 +0x29 fp=0xc0001b7c00 sp=0xc0001b7bd0 pc=0x5c94c9
bufio.(*Reader).fill(0xc00028a000)
	/snap/go/current/src/bufio/bufio.go:106 +0xff fp=0xc0001b7c38 sp=0xc0001b7c00 pc=0x60b01f
bufio.(*Reader).Peek(0xc00028a000, 0x1)
	/snap/go/current/src/bufio/bufio.go:144 +0x5d fp=0xc0001b7c58 sp=0xc0001b7c38 pc=0x60b17d
github.com/valyala/fasthttp.(*Server).serveConn(0xc0001a4400, {0xd151a0?, 0xc00009a008})
	/home/waplay/go/pkg/mod/github.com/valyala/fasthttp@v1.47.0/server.go:2176 +0x58e fp=0xc0001b7ec8 sp=0xc0001b7c58 pc=0x84a36e
github.com/valyala/fasthttp.(*Server).serveConn-fm({0xd151a0?, 0xc00009a008?})
	<autogenerated>:1 +0x39 fp=0xc0001b7ef0 sp=0xc0001b7ec8 pc=0x85a879
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc00011ba40, 0xc0000a8000)
	/home/waplay/go/pkg/mod/github.com/valyala/fasthttp@v1.47.0/workerpool.go:224 +0xa9 fp=0xc0001b7fa0 sp=0xc0001b7ef0 pc=0x856aa9
github.com/valyala/fasthttp.(*workerPool).getCh.func1()
	/home/waplay/go/pkg/mod/github.com/valyala/fasthttp@v1.47.0/workerpool.go:196 +0x38 fp=0xc0001b7fe0 sp=0xc0001b7fa0 pc=0x856818
runtime.goexit()
	/snap/go/current/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001b7fe8 sp=0xc0001b7fe0 pc=0x4ad101
created by github.com/valyala/fasthttp.(*workerPool).getCh
	/home/waplay/go/pkg/mod/github.com/valyala/fasthttp@v1.47.0/workerpool.go:195 +0x1b0

goroutine 34 [sleep]:
runtime.gopark(0x144b41600494?, 0xb92a20?, 0x40?, 0x3d?, 0xc111b8af5dbbbdfd?)
	/snap/go/current/src/runtime/proc.go:381 +0xd6 fp=0xc000284f88 sp=0xc000284f68 pc=0x47e2f6
time.Sleep(0x3b9aca00)
	/snap/go/current/src/runtime/time.go:195 +0x135 fp=0xc000284fc8 sp=0xc000284f88 pc=0x4a9f75
github.com/valyala/fasthttp.updateServerDate.func1()
	/home/waplay/go/pkg/mod/github.com/valyala/fasthttp@v1.47.0/header.go:2247 +0x1e fp=0xc000284fe0 sp=0xc000284fc8 pc=0x856efe
runtime.goexit()
	/snap/go/current/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000284fe8 sp=0xc000284fe0 pc=0x4ad101
created by github.com/valyala/fasthttp.updateServerDate
	/home/waplay/go/pkg/mod/github.com/valyala/fasthttp@v1.47.0/header.go:2245 +0x25

rax    0x478a693f04c46b1d
rbx    0xffffffff
rcx    0x270
rdx    0x4c46d8c
rdi    0x2d412a0
rsi    0x7f654f1a3be0
rbp    0x7ffd9cd598d0
rsp    0x7ffd9cd58420
r8     0x2d412b0
r9     0x7f654f1a4380
r10    0x2d2a010
r11    0x7f654f1a3be0
r12    0x2d412b0
r13    0x7ffd9cd599f0
r14    0x7ffd9cd59a28
r15    0x2dd1b50
rip    0xb01f95
rflags 0x10246
cs     0x33
fs     0x0
gs     0x0
`
-----------------------------------
OS Linux (Ubuntu 20.04)
Model used: https://gpt4all.io/models/ggml-vicuna-7b-1.1-q4_2.bin

**Comment by watcher60** [comment]
Probably better to post in the LocalAI project than here -- I would check you have Python3.10 or later as that tripped me up before (and got me to upgrade my Ubuntu to 22.04) and your processor supports AVX/AVX2

**Comment by aorumbayev** [comment]
@waplay please report the issue directly on localai repository, seems to be os/localai specific https://github.com/go-skynet/LocalAI/issues
