### ISSUE TITLE
Errors when running script

### ISSUE THREAD

**Issue by FrederikSchack** [aorumbayev/autogpt4all#6]
I've tried to install and uninstall a couple of times.

I'm on a Windows system with Git installed and I'm not a developer. I'm running the script in Git Bash.

1) As standard Make and Wget isn't installed with Git on Windows, so needs to be downloaded separately.

2) There is an error later in the script that seems to relate to replacing a temporary location with an actual location:
go mod edit -replace github.com/go-skynet/go-llama.cpp=/c/autogpt4all/LocalAI/go-llama
process_begin: CreateProcess(NULL, go mod edit -replace github.com/go-skynet/go-llama.cpp=/c/autogpt4all/LocalAI/go-llama, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:175: replace] Error 2

3) The rest of the script seems to be running fine, but the end result is that there's no local-ai file, which I'm supposed to run and there is no downloaded model. I think it may be related to point 2.

**Comment by aorumbayev** [comment]
@FrederikSchack ill keep this open for now, will probably replace the bash script with python so there is better windows compatibility, will keep you in loop on when its available

**Comment by FrederikSchack** [comment]
Thanks!

**Comment by Smartking1** [comment]
Any solution yet?

**Comment by aorumbayev** [comment]
@Smartking1 @FrederikSchack 
check latest readme, there are tweaks on script version and there is a python script alternative
