### ISSUE TITLE
`./local-ai` in run instruction, but such executable does not exist in `LocalAI` repo

### ISSUE THREAD

**Issue by hwamil** [aorumbayev/autogpt4all#7]
title

solution:

This is on Ubuntu. First you must install Go with `sudo apt install golang` so that you can build `local-ai` executable.
You build the executable by running `make build` in `LocalAI` repo dir.

**Comment by pehaem** [comment]
ok thanks

**Comment by pehaem** [comment]
getting this error with docker when building localai:

ERROR: failed to solve: Unavailable: error reading from server: EOF
